title = "Microsoft Online RESTful API"

[microsoft]
domain = "https://yourdoamin.com"
endpoint = "https://graph.microsoft.com"  # for 21 viant https://microsoftgraph.chinacloudapi.cn
authorize_url = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize" # for 21 viant https://login.chinacloudapi.com/common/oauth2/v2.0/authorize
token_url = "https://login.microsoftonline.com/common/oauth2/v2.0/token" # for 21 viant https://login.chinacloudapi.com/common/oauth2/v2.0/token
client_id = "your microsoft client id"
client_secret = "your microsoft client secret"
tenant_id = "your tenant id"
scope = "offline_access User.ReadWrite.All Directory.ReadWrite.All Directory.AccessAsUser.All"

[app]
listen_addr = ":8088"
access_key = "api gateway access key"
access_secret = "api getway access secret"
